app:
  frontend:
    url: http://localhost:3000  # URL of the frontend application
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/jobportal-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope: profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

jwt:
  signing:
    key: mysecretkey1234567890mysecretkey1234567890

springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expose all actuator endpoints

  tracing:
    enabled: true
    otlp:
      tracing:
        endpoint: http://localhost:4318/v1/traces
    export:
      otlp:
        enabled: true
        endpoint: http://localhost:4317 # This is the default OTLP endpoint
        headers:
          "X-OTLP-Protocol": "grpc"   # Optional, if needed for OTLP gRPC communication

  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://localhost:4317 # Same endpoint for metrics export
